name: Create Matrix Action

description: This action creates a matrix json file from an input string.

inputs:
  
  matrix:
    required: true
    description: The string that will be parsed for creating the matrix.

runs:
  using: docker
  image: 'Dockerfile'

branding:
  icon: test_tube
  color: black
