name: Create Matrix Action
description: This action creates a non-square matrix from an input string.

inputs:
  matrix:
    required: true
    description: The matrix string definition.

runs:
  using: docker
  image: 'Dockerfile'

branding:
  icon: grid
  color: purple
