name: Test Workflow
on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:

  create_matrix:
    
    runs-on: ubuntu-latest  
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run Action
        uses: ./
        with:
          input_matrix_string: |
            python-version {2.7}, django-version {1.7,1.8,1.9,1.10,1.11}, database {sqlite,mysql,postgres}
            python-version {3.6}, django-version {1.8,1.9,1.10,1.11,2.0,2.1,2.2,3.0,3.1,3.2}, database {sqlite,mysql,postgres}
            python-version {3.7}, django-version {2.0,2.1,2.2,3.0,3.1,3.2}, database {sqlite,mysql,postgres}
            python-version {3.8}, django-version {2.2,3.0,3.1,3.2}, database {sqlite,mysql,postgres}
            python-version {3.9}, django-version {2.2,3.0,3.1,3.2}, database {sqlite,mysql,postgres}
            python-version {3.10}, django-version {3.2,4.0}, database {sqlite,mysql,postgres}
          
          output_matrix_json: ./matrix.json
      
      - name: Set matrix output variable with matrix.json file content
        id: set-matrix
        run: |
          echo "::set-output name=matrix::$(cat ./matrix.json)" 

  test:
    
    needs: create_matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        include: ${{fromJson(needs.create_matrix.outputs.matrix)}}
      
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      
      - name: Upgrade pip version
        run: |
          pip install pip --upgrade
      
      - name: Install django
        run: |
          pip install "Django~=${{ matrix.django-version }}"
      
      - name: Debug matrix versions
        run: |
          echo "Python ${{ matrix.python-version }} + Django ${{ matrix.django-version }} + Database ${{ matrix.database }}"
          echo "Python: `python --version`"
          echo "Django: `django-admin --version`"
          
